name: Regression Testing

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
        env:
          # prevents lint warnings from being errors
          CI: false
